# network
batch: 1
epoch: 300
bilstm_layers: 1
word_dim: 200
lstm_dim: 100
out_dim: 100
type_dim: 10
beta: 0.8
dist_dim: 10
drop_i: 0.5
drop_m: 0.0
drop_o: 0.3
lr: 0.001
gc: 10
reg: 0.0001
opt: adam
patience: 10
unk_w_prob: 0.5
min_w_freq: 1
walks_iter: 4

# data based
train_data: ../data/Dialogue/processed_new/dialogue_dev_train.data
test_data: ../data/Dialogue/processed_new/dialogue_dev_test.data
embeds: ../embeds/glove.6B.200d.txt
folder: ../results/docred-test
save_pred: test

# options (chosen from parse input otherwise false)
lowercase: false
plot: true
show_class: false
param_avg: true
early_stop: false
save_model: true
types: true
context: false
dist: true
freeze_words: true

# extra
seed: 0
shuffle_data: true
label2ignore: 1:NR:2
primary_metric: micro_f
direction: l2r+r2l
include_pairs: ['PER-PER', 'PER-GPE', 'PER-ORG', 'PER-STRING', 'PER-VALUE', 'GPE-PER', 'GPE-GPE', 'GPE-ORG', 'GPE-STRING', 'GPE-VALUE', 'ORG-PER', 'ORG-GPE', 'ORG-ORG', 'ORG-STRING', 'ORG-VALUE', 'STRING-PER', 'STRING-GPE', 'STRING-ORG', 'STRING-STRING', 'STRING-VALUE', 'VALUE-PER', 'VALUE-GPE', 'VALUE-ORG', 'VALUE-STRING', 'VALUE-VALUE']
classify_pairs: ['PER-PER', 'PER-GPE', 'PER-ORG', 'PER-STRING', 'PER-VALUE', 'GPE-PER', 'GPE-GPE', 'GPE-ORG', 'GPE-STRING', 'GPE-VALUE', 'ORG-PER', 'ORG-GPE', 'ORG-ORG', 'ORG-STRING', 'ORG-VALUE', 'STRING-PER', 'STRING-GPE', 'STRING-ORG', 'STRING-STRING', 'STRING-VALUE', 'VALUE-PER', 'VALUE-GPE', 'VALUE-ORG', 'VALUE-STRING', 'VALUE-VALUE']
edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
window: 
