# network
batch: 1
epoch: 50
bilstm_layers: 1
word_dim: 200
lstm_dim: 100
out_dim: 100
type_dim: 10
beta: 0.8
dist_dim: 10
drop_i: 0.5
drop_m: 0.0
drop_o: 0.3
lr: 0.002
gc: 10
reg: 0.0001
opt: adam
patience: 10
unk_w_prob: 0.5
min_w_freq: 1
walks_iter: 4

# data based
train_data: ../data/DocRED/processed/dev_train.data
test_data: ../data/DocRED/processed/dev_dev.data
embeds: ../embeds/PubMed-CDR.txt
folder: ../results/docred-test
save_pred: test

# options (chosen from parse input otherwise false)
lowercase: false
plot: true
show_class: false
param_avg: true
early_stop: false
save_model: true
types: true
context: true
dist: true
freeze_words: true

# extra
seed: 0
shuffle_data: true
label2ignore: 1:NR:2
primary_metric: micro_f
direction: l2r+r2l
include_pairs: ['PER-PER', 'PER-ORG', 'PER-LOC', 'PER-TIME', 'PER-NUM',
                'PER-MISC', 'ORG-PER', 'ORG-ORG', 'ORG-LOC', 'ORG-TIME',
                'ORG-NUM', 'ORG-MISC', 'LOC-PER', 'LOC-ORG', 'LOC-LOC',
                'LOC-TIME', 'LOC-NUM', 'LOC-MISC', 'TIME-PER', 'TIME-ORG',
                'TIME-LOC', 'TIME-TIME', 'TIME-NUM', 'TIME-MISC', 'NUM-PER',
                'NUM-ORG', 'NUM-LOC', 'NUM-TIME', 'NUM-NUM', 'NUM-MISC',
                'MISC-PER', 'MISC-ORG', 'MISC-LOC', 'MISC-TIME', 'MISC-NUM', 'MISC-MISC']
classify_pairs: ['PER-PER', 'PER-ORG', 'PER-LOC', 'PER-TIME', 'PER-NUM',
                 'PER-MISC', 'ORG-PER', 'ORG-ORG', 'ORG-LOC', 'ORG-TIME',
                 'ORG-NUM', 'ORG-MISC', 'LOC-PER', 'LOC-ORG', 'LOC-LOC',
                 'LOC-TIME', 'LOC-NUM', 'LOC-MISC', 'TIME-PER', 'TIME-ORG',
                 'TIME-LOC', 'TIME-TIME', 'TIME-NUM', 'TIME-MISC', 'NUM-PER',
                 'NUM-ORG', 'NUM-LOC', 'NUM-TIME', 'NUM-NUM', 'NUM-MISC',
                 'MISC-PER', 'MISC-ORG', 'MISC-LOC', 'MISC-TIME', 'MISC-NUM', 'MISC-MISC']
edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
window: 
